### ISSUE TITLE
Breaks when interacting with Artifact of Metamorphosis

### ISSUE THREAD

**Issue by AlvaIgnus** [RegalTurtle24/PartialEclipse#2]
Hey there, congrats on the mod btw. I tried to use it and Metamorphosis at the same time and instead of loading me into the world I was in an empty skybox and didn't even load in a character. I know nothing about coding and made this account for this, but I imagine the eclipse buff is tied to character selection? idk
I have quite a few other mods installed, here is my r2modman code in case you're having trouble reproducing it or this is an interaction issue: 01864df0-c12e-7ff5-2571-95f810d5727b

**Comment by RegalTurtle** [comment]
After a little bit of testing, it looks like the problem happens with just SS2, and I was able to reproduce it after only installing Starstorm 2 and all of its dependencies. They seem to be aware as they have a couple of issues related to it and it is on their to-do. Thanks for reaching out!
